name: secret_dms
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fpdart: ^0.1.0
  appwrite: ^6.0.0
  go_router: ^4.1.0
  get_it: ^7.2.0
  flutter_riverpod: ^1.0.4
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  flutter_svg: ^1.1.1+1
  iconsax: ^0.0.8
  uni_links: ^0.5.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true

  # Images used in the app
  assets:
    - .env
    - assets/images/

  # Fonts used in the app
  fonts:
    - family: AppFontLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: AppFontRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: AppFontMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: AppFontSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: AppFontBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

